export const ROLES = [
  'CEO', 'SUPER_ADMIN', 'CPO', 'PRODUCT_MANAGER', 'PRODUCT_DESIGNER',
  'PRODUCT_DESIGN_TEAM_LEAD', 'CTO', 'ENG_TEAM_LEAD_FRONTEND', 'ENG_TEAM_LEAD_BACKEND',
  'ENG_TEAM_LEAD_CLOUD_DEVOPS', 'ENG_TEAM_LEAD_QA', 'FRONTEND_DEVELOPER',
  'BACKEND_DEVELOPER', 'CLOUD_DEVOPS_ENGINEER', 'QA_ENGINEER', 'CBO',
  'BRAND_TEAM_LEAD', 'BRAND_DESIGNER', 'GRAPHICS_DESIGNER', 'MOTION_DESIGNER',
  'COO', 'BA_TEAM_LEAD', 'DATA_ANALYST', 'BUSINESS_ANALYST', 'CAB_MEMBER', 'PRODUCT_OWNER',
] as const;

export const MODULES = ['PRODUCT', 'ENGINEERING', 'BRAND', 'BUSINESS_ANALYSIS'] as const;

export const ENGINEERING_DISCIPLINES = ['FRONTEND', 'BACKEND', 'CLOUD_DEVOPS', 'QA'] as const;

export const TASK_STATUSES = [
  'DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'SUBMITTED_FOR_REVIEW', 'LEAD_APPROVED',
  'CPO_APPROVED', 'CTO_APPROVED', 'CBO_APPROVED', 'COO_APPROVED', 'DONE',
  'REJECTED', 'REWORK', 'BACKLOG', 'READY_FOR_REVIEW', 'REWORK_REQUESTED', 'REOPENED',
] as const;

export const PROJECT_STATUSES = ['DRAFT', 'ACTIVE', 'ON_HOLD', 'COMPLETED', 'CANCELLED'] as const;

export const CHANGE_REQUEST_TYPES = ['SCOPE', 'TIMELINE', 'BUDGET', 'RESOURCE'] as const;
export const CHANGE_REQUEST_STATUSES = ['OPEN', 'IN_REVIEW', 'APPROVED', 'APPROVED_WITH_CONDITIONS', 'REJECTED', 'DEFERRED'] as const;

export const NOTIFICATION_EVENTS = [
  'TASK_ASSIGNED', 'TASK_STATUS_CHANGE', 'APPROVAL_REQUESTED', 'APPROVED',
  'REJECTED', 'DEADLINE_APPROACHING', 'CAB_DECISION_PUBLISHED', 'MENTIONED',
  'PROJECT_ADDED', 'LOAN_REQUEST_SUBMITTED', 'LOAN_REQUEST_APPROVED',
  'LOAN_REQUEST_REJECTED', 'ASSET_PUBLISHED', 'COMMENT_ADDED',
] as const;

export const NOTIFICATION_CHANNELS = ['IN_APP', 'EMAIL', 'SLACK'] as const;
